blank_issues_enabled: true
contact_links:
  # - name: Ask a question
  #   url: ./../../discussions
  #   about: Please report security vulnerabilities here.
  - name: JSON Schema Slack
    url: https://json-schema.org/slack
    about: Get async support and discussion from the community and maintainers