name: Greet on User First PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
        run: npm install @octokit/core@5.1.0 

      - uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const authorLogin = context.payload.pull_request.user.login;

            const { Octokit } = require("@octokit/core");
            const mygithub = new octokit({
                request: { fetch: fetch,},
                auth: process.env.GITHUB_TOKEN,
              });

            const firstPR = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_requests: {
                state: 'closed',
                author: authorLogin,
              },
            });
            
            console.log(firstPR.data.length); 

            if (firstPR.data.length === 1) {
              const greetingMessage = ` Congratulations, @${authorLogin} for your first pull request merge in this repository! 🎉🎉. Thanks for your contribution to JSON Schema! `;

              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: greetingMessage
              });
            }